### ISSUE TITLE
errors in gateway-win-x86_64.asm

### ISSUE THREAD

**Issue by BertaTM** [rdbo/jnihook#7]
1. using **x64 Native Tools Command Prompt** causes cmake to fail, **x86 Native Tools Command Prompt** works fine.
2. in step 3, everything compiles fine until gateway-win-x86_64.asm, where I receive the following error: **error A2013:.MODEL must precede this directive**. When adding **.MODEL FLAT, C** to fix this issue, I receive an undefined error for every register used.

I don't really know what else I could do to fix this. Help is much appreciated.

**Comment by rdbo** [comment]
The gateway is for x64, so it won't build on x86 native tools.
You need to investigate why CMake fails in the x64 Native Tools, and fix that. Then use CMake with it.

**Comment by BertaTM** [comment]
literally haven't touched anything and tried it again with the x64 native tools, everything worked this time.
