### ISSUE TITLE
Arch Info

### ISSUE THREAD

**Issue by Ezriral** [rdbo/jnihook#8]
does it work with ARM 32bit, ARM 64bit ? or does it only work for emulators because i just see the x86 ASM files.

thank you

**Comment by rdbo** [comment]
Only works currently on x86_64 JVMs (OpenJDK, OracleJDK), not any other arches

**Comment by pinkestflamingo** [comment]
> Only works currently on x86_64 JVMs (OpenJDK, OracleJDK), not any other arches

Will you add support for ARM 64 anytime soon?

**Comment by EarzuChan** [comment]
Hey! If you want to hook methods on Android devices (they use ARM architecture, though I'm not sure if that's what you're referring to), try using libraries like LSPlant (https://github.com/LSPosed/LSPlant).

**Comment by rdbo** [comment]
This is no longer an issue for JNIHook on master, it doesn't have arch-specific code anymore, and I plan to keep it that way
Should work for any architecture now
Everything should be 100% working when 2.0 releases
